<?php

require "data/posts.php";

$design = [
    $posts["design"][0],
    $posts["design"][1],
    $posts["design"][2]
];

$dev = [
    $posts["development"][0],
    $posts["development"][1],
    $posts["development"][2]
];

$accessibility = [
    $posts["accessibility"][0],
    $posts["accessibility"][1],
    $posts["accessibility"][2]
];

?>



<main id="home" class="p-3">
    <h1 class="text-center m-5">Ze blog</h1>
    <section class="my-5">
        <h2>Design</h2>
        <ul class="row p-0">
            
            <?php foreach($design as $items) { ?>
            
            <li class="col m-1">
                <article class="card">
                    <header class="card-header p-0">
                        <img src="https://picsum.photos/id/1/550/250" class="card-img-top" alt="" />
                        <h3 class="card-title px-2 py-3">
                            
                            <?= $items["title"] ?>
                        </h3>
                    </header>
                    <section class="card-body p-2">
                        <p class="card-text">
                            
                            <?= $items["excerpt"] ?>
                            
                        </p>
                    </section>
                    <footer class="p-2">
                        <a href="#" class="btn btn-primary">Lire l'article</a>
                    </footer>
                </article>
            </li>
            <!--<li class="col m-1">
                <article class="card">
                    <header class="card-header p-0">
                        <img src="https://picsum.photos/id/17/550/250" class="card-img-top" alt="" />
                        <h3 class="card-title px-2 py-3">
                             <?= $items["title"] ?>
                        </h3>
                    </header>
                    <section class="card-body p-2">
                        <p class="card-text">
                             <?= $items["excerpt"] ?>
                        </p>
                    </section>
                    <footer class="p-2">
                        <a href="#" class="btn btn-primary">Lire l'article</a>
                    </footer>
                </article>
            </li>
            <li class="col m-1">
                <article class="card">
                    <header class="card-header p-0">
                        <img src="https://picsum.photos/id/28/550/250" class="card-img-top" alt="" />
                        <h3 class="card-title px-2 py-3">
                             <?= $items["title"] ?>
                        </h3>
                    </header>
                    <section class="card-body p-2">
                        <p class="card-text">
                             <?= $items["excerpt"] ?>
                        </p>
                    </section>
                    <footer class="p-2">
                        <a href="#" class="btn btn-primary">Lire l'article</a>
                    </footer>
                </article>
            </li>-->
            <?php } ?>
        </ul>
    </section>
    <section class="my-5">
        <h2>Development</h2>
        <ul class="row p-0">
            
             <?php foreach($design as $items) { ?>
             
            <li class="col m-1">
                <article class="card">
                    <header class="card-header p-0">
                        <img src="https://picsum.photos/id/32/550/250" class="card-img-top" alt="" />
                        <h3 class="card-title px-2 py-3">
                             <?= $items["title"] ?>
                        </h3>
                    </header>
                    <section class="card-body p-2">
                        <p class="card-text">
                             <?= $items["excerpt"] ?>
                        </p>
                    </section>
                    <footer class="p-2">
                        <a href="#" class="btn btn-primary">Lire l'article</a>
                    </footer>
                </article>
            </li>
            <!--<li class="col m-1">
                <article class="card">
                    <header class="card-header p-0">
                        <img src="https://picsum.photos/id/44/550/250" class="card-img-top" alt="" />
                        <h3 class="card-title px-2 py-3">
                            <?= $items["title"] ?>
                        </h3>
                    </header>
                    <section class="card-body p-2">
                        <p class="card-text">
                            <?= $items["excerpt"] ?>
                        </p>
                    </section>
                    <footer class="p-2">
                        <a href="#" class="btn btn-primary">Lire l'article</a>
                    </footer>
                </article>
            </li>
            <li class="col m-1">
                <article class="card">
                    <header class="card-header p-0">
                        <img src="https://picsum.photos/id/58/550/250" class="card-img-top" alt="" />
                        <h3 class="card-title px-2 py-3">
                            <?= $items["title"] ?>
                        </h3>
                    </header>
                    <section class="card-body p-2">
                        <p class="card-text">
                            <?= $items["excerpt"] ?>
                        </p>
                    </section>
                    <footer class="p-2">
                        <a href="#" class="btn btn-primary">Lire l'article</a>
                    </footer>
                </article>
            </li> -->
            <?php } ?>
        </ul>
    </section>
    <section class="my-5">
        <h2>Accessibility</h2>
        <ul class="row p-0">
             <?php foreach($design as $items) { ?>
            <li class="col m-1">
                <article class="card">
                    <header class="card-header p-0">
                        <img src="https://picsum.photos/id/67/550/250" class="card-img-top" alt="" />
                        <h3 class="card-title px-2 py-3">
                            <?= $items["title"] ?>
                        </h3>
                    </header>
                    <section class="card-body p-2">
                        <p class="card-text">
                            <?= $items["excerpt"] ?>
                        </p>
                    </section>
                    <footer class="p-2">
                        <a href="#" class="btn btn-primary">Lire l'article</a>
                    </footer>
                </article>
            </li>
           <!--  <li class="col m-1">
                <article class="card">
                    <header class="card-header p-0">
                        <img src="https://picsum.photos/id/73/550/250" class="card-img-top" alt="" />
                        <h3 class="card-title px-2 py-3">
                            Titre de l'article
                        </h3>
                    </header>
                    <section class="card-body p-2">
                        <p class="card-text">
                            Extrait de l'article
                        </p>
                    </section>
                    <footer class="p-2">
                        <a href="#" class="btn btn-primary">Lire l'article</a>
                    </footer>
                </article>
            </li>
            <li class="col m-1">
                <article class="card">
                    <header class="card-header p-0">
                        <img src="https://picsum.photos/id/81/550/250" class="card-img-top" alt="" />
                        <h3 class="card-title px-2 py-3">
                            Titre de l'article
                        </h3>
                    </header>
                    <section class="card-body p-2">
                        <p class="card-text">
                            Extrait de l'article
                        </p>
                    </section>
                    <footer class="p-2">
                        <a href="#" class="btn btn-primary">Lire l'article</a>
                    </footer>
                </article>
            </li> -->
            <?php } ?>
        </ul>
    </section>
</main>